# From: http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %PYTHON% %PYTHON_ARCH%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build psutil
  - conda update -q conda
  - conda info -a
  - "conda-env create -f gds_py/gds_py.yml"
  - cmd: call %PYTHON%\Scripts\activate.bat
  - conda activate gds

test_script:
  - python -c "import os; print(os.getcwd())"
  - "jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=120 gds_py/check_py_stack.ipynb"
 #- cd content/labs
 #- jupyter nbconvert --execute --ExecutePreprocessor.timeout=120 *.ipynb
